server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.walker.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: spring-boot-demo-provider-make
  jackson:
    default-property-inclusion: non_null  # JSON返回值去除null和空字段
    serialization:
      write-dates-as-timestamps: true  # JSON返回时间为时间戳格式
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud01?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                   #最小维持连接数
      initial-size: 5               #初始化连接数
      max-total: 20                 #最大连接数
      max-wait-millis: 1000         #等待连接的最大超时时间
#  zipkin:
#    base-url: http://192.168.2.217:9411/
#  #开发环境设置为1
#  sleuth:
#    sampler:
#      probability: 1

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
  client:
    register-with-eureka: true
    enabled: true
    service-url:
#      defaultZone: http://jixiang:jixiang2019@localhost:7001/eureka
      defaultZone: http://eureka:7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka:7003.com:7003/eureka
    healthcheck:
      enabled: true

info:
  java:
    version: ${java.version}
  app.name: ${spring.application.name}
  company.name: www.toponebuyer.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

#management:
#  endpoints:
#    web:
#      exposure:
#        # spring-boot-starter-actuator 2.0版本以上得这么配置，将接口暴露出来，如果要暴露全部节点使用include: "*"
#        include: refresh,health,info
## INFO ENDPOINT CONFIGURATION

#evn: dev
#branch: master

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

